sudo: true

language: node_js
node_js:
    - "6.9.4"
    - "7.4.0"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export isTravis=1

script: "grunt"

