dist: trusty
sudo: required

language: node_js
node_js:
    - "6.9.4"
    - "7.4.0"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - export isTravis=1

script: "grunt"

